sudo: false
language: python
python:
  - "2.7"
notifications:
  slack: ooi-dev:e6WpBt9NHHw1YJjRKuYHkhYr

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda env create -f conda_env.yml
  - source activate ion
  - python setup.py develop

# command to run tests
script:
  - nosetests
