name: ion
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - cython
  - matplotlib
  - numexpr>=2.8.7
  - numpy>=1.26.0
  - scipy>=1.11.3
  - gsw>=3.6.17
  - ppigrf>=13.0
  - mkdocs-material
  - mkdocstrings
