site_name: Ocean Observatories Initiative Ion Functions
theme:
  name: "material"
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path

plugins:
  - mkdocstrings

nav:
  - Ion Functions Overview: index.md
  - Reference:
    - CTD Functions: ctd_functions.md
    - CO2 Functions: co2_functions.md
  - QC/Testing: qc-tests.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
