#!/usr/bin/env python
"""
Functions for computing OOI velocity family data products.

Covers VELPTMN (Mean Point Water Velocity) and VELPTTU (Turbulent Point Water
Velocity) for the following instrument classes: VELPT-A/B/D/J (Nortek
Aquadopp), VEL3D-A (FSI ACM-3D-MP, RSN), VEL3D-B (Nobska MAVS-4), VEL3D-C/D
(Nortek Vector), VEL3D-K (Nortek Aquadopp II on McLane WFP), and VEL3D-L
(FSI ACM-Plus, Scripps).
"""

import numpy as np
from numpy import sin, cos, radians

from ion_functions.data.generic_functions import magnetic_declination, magnetic_correction

# NOTE:
#    The previous version of this module had each function return an
#    array of all fill values (-9999) if the lat or lon is invalid. This
#    should not occur. Really lat and lon should be checked and handled
#    in the QAQC functions, and only apply a fill value for the single
#    instance of invalid lat & lon rather than the whole array. I
#    believe they were coded here for testing purposes. The part that
#    returned the fill values now instead just raises the ValueError
#    exception.
#               -Stuart Pearce
#               (this message should be removed if/when the lats & lons
#               are checked in the QAQC functions)
# from exceptions import ValueError

### Constants (VEL3D-K) ###
# XYZ_TRANSFORMS is a dictionary constant that is generated when the
# module is first imported. XYZ_TRANSFORMS is generated by the
# generate_beam_transforms function and must be created after the
# function is declared. Therefore XYZ_TRANSFORMS is not here in the
# constants section. See line 1649.

"""
            Order of functions in this module

Functions that directly calculate data products:

    fsi_acm_rsn_east               -- calculates VELPTMN-VLE_L1 from VEL3D-A
    fsi_acm_rsn_north              -- calculates VELPTMN-VLN_L1 from VEL3D-A
    fsi_acm_sio_east               -- calculates VELPTMN-VLE_L1 from VEL3D-L
    fsi_acm_sio_north              -- calculates VELPTMN-VLN_L1 from VEL3D-L
    fsi_acm_up_profiler_ascending  -- calculates VELPTMN-VLU-ASC_L1 from VEL3D-AL
    fsi_acm_up_profiler_descending -- calculates VELPTMN-VLU-DSC_L1 from VEL3D-AL

    nobska_mag_corr_east   -- calculates VELPTTU-VLE_L1 from VEL3D-B
    nobska_mag_corr_north  -- calculates VELPTTU-VLN_L1 from VEL3D-B
    nobska_scale_up_vel    -- calculates VELPTTU-VLU_L1 from VEL3D-B

    nortek_mag_corr_east   -- calculates VELPTTU-VLE_L1 from VEL3D-CD
    nortek_mag_corr_north  -- calculates VELPTTU-VLN_L1 from VEL3D-CD
    nortek_up_vel          -- calculates VELPTTU-VLU_L1 from VEL3D-CD

    vel3dk_east            -- calculates VELPTTU-VLE_L1 from VEL3D-K
    vel3dk_north           -- calculates VELPTTU-VLN_L1 from VEL3D-K
    vel3dk_up              -- calculates VELPTTU-VLU_L1 from VEL3D-K

    velpt_mag_corr_east    -- calculates VELPTMN-VLE_L1 from VELPT-ABDJ
    velpt_mag_corr_north   -- calculates VELPTMN-VLN_L1 from VELPT-ABDJ
    velpt_up_vel           -- calculates VELPTMN-VLU_L1 from VELPT-ABDJ

Subfunctions:

    fsi_acm_horz_vel          -- used by vel3d-a,l
    fsi_acm_nautical_heading  -- used by vel3d-a
    fsi_acm_compass_cal       -- used by vel3d-a
    generate_beam_transforms  -- used by vel3d-k
    get_XYZ_transform         -- used by vel3d-k
    generate_ENU_transform    -- used by vel3d-k
    vel3dk_transform          -- used by vel3d-k
    vel_mag_correction        -- used by most of the horz vel fns

Helper sub-functions:

    valid_lat
    valid_lon

"""


# wrapper functions for use in ION
def fsi_acm_rsn_east(vp1, vp3, hx, hy, hdg_cal, hx_cal, hy_cal, lat, lon, timestamp):
    """
    OOI wrapper for VELPTMN-VLE_L1 eastward velocity from VEL3D-A (RSN).

    Derives the instrument heading from field direction cosines and an
    8-point spin calibration, then calls fsi_acm_horz_vel to compute the
    eastward velocity component.

    Parameters
    ----------
    vp1 : array_like
        Raw beam velocity from the port stinger finger;
        VELPTMN-VP1_L0 [cm/s].
    vp3 : array_like
        Raw beam velocity from the starboard stinger finger;
        VELPTMN-VP3_L0 [cm/s].
    hx : array_like
        Direction cosine of the magnetic field projected onto the
        instrument x-axis; VELPTMN-HXX_L0.
    hy : array_like
        Direction cosine of the magnetic field projected onto the
        instrument y-axis; VELPTMN-HYY_L0.
    hdg_cal : array_like
        8-element vector of reference ACM headings from a compass
        calibration spin test [degrees clockwise from magnetic north].
    hx_cal : array_like
        8-element vector of direction cosines of the magnetic field
        projected along the instrument x-axis during a calibration spin.
    hy_cal : array_like
        8-element vector of direction cosines of the magnetic field
        projected along the instrument y-axis during a calibration spin.
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].

    Returns
    -------
    u : ndarray
        Eastward velocity VELPTMN-VLE_L1 in true Earth coordinates [m/s].

    See Also
    --------
    fsi_acm_horz_vel : Core algorithm; use directly for multi-output
        access.
    """
    # calculate the headings from the field direction cosines hx and hy and the cal data.
    hdg = fsi_acm_nautical_heading(hx, hy, hdg_cal, hx_cal, hy_cal)

    # call the worker function which calculates both the east and north data products
    (u, _) = fsi_acm_horz_vel(vp1, vp3, hdg, lat, lon, timestamp)
    return u


def fsi_acm_rsn_north(vp1, vp3, hx, hy, hdg_cal, hx_cal, hy_cal, lat, lon, timestamp):
    """
    OOI wrapper for VELPTMN-VLN_L1 northward velocity from VEL3D-A (RSN).

    Derives the instrument heading from field direction cosines and an
    8-point spin calibration, then calls fsi_acm_horz_vel to compute the
    northward velocity component.

    Parameters
    ----------
    vp1 : array_like
        Raw beam velocity from the port stinger finger;
        VELPTMN-VP1_L0 [cm/s].
    vp3 : array_like
        Raw beam velocity from the starboard stinger finger;
        VELPTMN-VP3_L0 [cm/s].
    hx : array_like
        Direction cosine of the magnetic field projected onto the
        instrument x-axis; VELPTMN-HXX_L0.
    hy : array_like
        Direction cosine of the magnetic field projected onto the
        instrument y-axis; VELPTMN-HYY_L0.
    hdg_cal : array_like
        8-element vector of reference ACM headings from a compass
        calibration spin test [degrees clockwise from magnetic north].
    hx_cal : array_like
        8-element vector of direction cosines of the magnetic field
        projected along the instrument x-axis during a calibration spin.
    hy_cal : array_like
        8-element vector of direction cosines of the magnetic field
        projected along the instrument y-axis during a calibration spin.
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].

    Returns
    -------
    v : ndarray
        Northward velocity VELPTMN-VLN_L1 in true Earth coordinates
        [m/s].

    See Also
    --------
    fsi_acm_horz_vel : Core algorithm; use directly for multi-output
        access.
    """
    # calculate the headings from the field direction cosines hx and hy and the cal data.
    hdg = fsi_acm_nautical_heading(hx, hy, hdg_cal, hx_cal, hy_cal)

    # call the worker function which calculates both the east and north data products
    (_, v) = fsi_acm_horz_vel(vp1, vp3, hdg, lat, lon, timestamp)
    return v


def fsi_acm_sio_east(vp1, vp3, hdg, lat, lon, timestamp):
    """
    OOI wrapper for VELPTMN-VLE_L1 eastward velocity from VEL3D-L (SIO).

    Calls fsi_acm_horz_vel with the instrument-reported heading to
    compute the eastward velocity component. No compass calibration
    correction is applied for Scripps deployments.

    Parameters
    ----------
    vp1 : array_like
        Raw beam velocity from the port stinger finger;
        VELPTMN-VP1_L0 [cm/s].
    vp3 : array_like
        Raw beam velocity from the starboard stinger finger;
        VELPTMN-VP3_L0 [cm/s].
    hdg : array_like
        ACM heading as reported by the instrument [degrees clockwise
        from magnetic north]; VELPTMN-HDG_L0.
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].

    Returns
    -------
    u : ndarray
        Eastward velocity VELPTMN-VLE_L1 in true Earth coordinates [m/s].

    See Also
    --------
    fsi_acm_horz_vel : Core algorithm; use directly for multi-output
        access.
    """
    # call the worker function which calculates both the east and north data products
    (u, _) = fsi_acm_horz_vel(vp1, vp3, hdg, lat, lon, timestamp)
    return u


def fsi_acm_sio_north(vp1, vp3, hdg, lat, lon, timestamp):
    """
    OOI wrapper for VELPTMN-VLN_L1 northward velocity from VEL3D-L (SIO).

    Calls fsi_acm_horz_vel with the instrument-reported heading to
    compute the northward velocity component. No compass calibration
    correction is applied for Scripps deployments.

    Parameters
    ----------
    vp1 : array_like
        Raw beam velocity from the port stinger finger;
        VELPTMN-VP1_L0 [cm/s].
    vp3 : array_like
        Raw beam velocity from the starboard stinger finger;
        VELPTMN-VP3_L0 [cm/s].
    hdg : array_like
        ACM heading as reported by the instrument [degrees clockwise
        from magnetic north]; VELPTMN-HDG_L0.
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].

    Returns
    -------
    v : ndarray
        Northward velocity VELPTMN-VLN_L1 in true Earth coordinates
        [m/s].

    See Also
    --------
    fsi_acm_horz_vel : Core algorithm; use directly for multi-output
        access.
    """
    # call the worker function which calculates both the east and north data products
    (_, v) = fsi_acm_horz_vel(vp1, vp3, hdg, lat, lon, timestamp)
    return v


def fsi_acm_up_profiler_ascending(vp1, vp3, vp4):
    """
    Compute VELPTMN-VLU-ASC_L1 upward velocity during profiler ascent.

    Calculates the upward velocity data product for VEL3D series A and L
    FSI ACM instruments during profiler ascent. Uses vp1, vp3, and vp4
    to avoid contamination from the sheet-flow wake of the stinger's
    central post, which affects vp2 during ascent.

    Parameters
    ----------
    vp1 : array_like
        Raw beam velocity from the port stinger finger;
        VELPTMN-VP1_L0 [cm/s].
    vp3 : array_like
        Raw beam velocity from the starboard stinger finger;
        VELPTMN-VP3_L0 [cm/s].
    vp4 : array_like
        Raw beam velocity from the upper stinger finger;
        VELPTMN-VP4_L0 [cm/s].

    Returns
    -------
    w : ndarray
        Upward velocity VELPTMN-VLU-ASC_L1 [m/s].

    Notes
    -----
    The MMP manual (Rev E, p. 8-30) contains an error in the upward
    velocity formula for ascent. The formula implemented here follows
    the corrected algorithm. Pitch and roll effects are considered
    negligible for profiler-mounted instruments.
    """
    # find the x-velocity in the instrument coordinate system
    x = -(vp1 + vp3) / np.sqrt(2.0)
    # the z-velocity in the instrument coordinate system is also the w velocity in the
    # earth coordinate system because the effects of pitch and roll are negligible.
    w = x - np.sqrt(2.0) * vp4
    # change units from cm/s to m/s
    return w / 100.0


def fsi_acm_up_profiler_descending(vp1, vp2, vp3):
    """
    Compute VELPTMN-VLU-DSC_L1 upward velocity during profiler descent.

    Calculates the upward velocity data product for VEL3D series A and L
    FSI ACM instruments during profiler descent. Uses vp1, vp2, and vp3
    to avoid contamination from the sheet-flow wake of the stinger's
    central post, which affects vp4 during descent.

    Parameters
    ----------
    vp1 : array_like
        Raw beam velocity from the port stinger finger;
        VELPTMN-VP1_L0 [cm/s].
    vp2 : array_like
        Raw beam velocity from the lower stinger finger;
        VELPTMN-VP2_L0 [cm/s].
    vp3 : array_like
        Raw beam velocity from the starboard stinger finger;
        VELPTMN-VP3_L0 [cm/s].

    Returns
    -------
    w : ndarray
        Upward velocity VELPTMN-VLU-DSC_L1 [m/s].

    Notes
    -----
    The MMP manual (Rev E, p. 8-30) contains an error in the upward
    velocity formula for descent. The formula implemented here follows
    the corrected algorithm. Pitch and roll effects are considered
    negligible for profiler-mounted instruments.
    """
    # find the x-velocity in the instrument coordinate system
    x = -(vp1 + vp3) / np.sqrt(2.0)
    # the z-velocity in the instrument coordinate system is also the w velocity in the
    # earth coordinate system because the effects of pitch and roll are negligible.
    w = -x + np.sqrt(2.0) * vp2
    # change units from cm/s to m/s
    return w / 100.0


def nobska_mag_corr_east(u, v, lat, lon, timestamp, z=0):
    """
    OOI wrapper for VELPTTU-VLE_L1 eastward velocity from VEL3D-B (Nobska).

    Converts units from cm/s to m/s and calls vel_mag_correction to
    apply the WMM magnetic declination rotation.

    Parameters
    ----------
    u : array_like
        Uncorrected eastward velocity in magnetic Earth frame [cm/s].
    v : array_like
        Uncorrected northward velocity in magnetic Earth frame [cm/s].
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    z : float or array_like, optional
        Depth of instrument relative to sea level [m], positive values
        only. Default is 0.

    Returns
    -------
    u_cor : ndarray
        Eastward velocity VELPTTU-VLE_L1 in true Earth frame [m/s].

    See Also
    --------
    vel_mag_correction : Core algorithm; use directly for multi-output
        access.
    """
   # Check for valid latitudes & longitudes
    if not valid_lat(lat) or not valid_lon(lon):
        # commented out next line according to NOTE above. -SP
        #return np.ones(u.shape, dtype=float) * -9999
        raise ValueError('Latitudes or Longitudes are not within the valid range!')

    # correct for magnetic declination
    u_cor = vel_mag_correction(u, v, lat, lon, timestamp, z)[0]
    u_cor = u_cor / 100.  # convert from cm/s to m/s

    # return true compass referenced East velocity in m/s
    return u_cor


def nobska_mag_corr_north(u, v, lat, lon, timestamp, z=0):
    """
    OOI wrapper for VELPTTU-VLN_L1 northward velocity from VEL3D-B (Nobska).

    Converts units from cm/s to m/s and calls vel_mag_correction to
    apply the WMM magnetic declination rotation.

    Parameters
    ----------
    u : array_like
        Uncorrected eastward velocity in magnetic Earth frame [cm/s].
    v : array_like
        Uncorrected northward velocity in magnetic Earth frame [cm/s].
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    z : float or array_like, optional
        Depth of instrument relative to sea level [m], positive values
        only. Default is 0.

    Returns
    -------
    v_cor : ndarray
        Northward velocity VELPTTU-VLN_L1 in true Earth frame [m/s].

    See Also
    --------
    vel_mag_correction : Core algorithm; use directly for multi-output
        access.
    """
   # check for valid latitudes & longitudes
    if not valid_lat(lat) or not valid_lon(lon):
        # commented out next line according to NOTE above. -SP
        #return np.ones(u.shape, dtype=float) * -9999
        raise ValueError('Latitudes or Longitudes are not within the valid range!')

    # correct for magnetic declination
    v_cor = vel_mag_correction(u, v, lat, lon, timestamp, z)[1]
    v_cor = v_cor / 100.  # convert from cm/s to m/s

    # return true compass referenced North velocity in m/s
    return v_cor


def nobska_scale_up_vel(w):
    """
    Compute VELPTTU-VLU_L1 upward velocity for VEL3D-B (Nobska MAVS-4).

    Converts the upward velocity from the Nobska MAVS-4 instrument from
    cm/s to m/s.

    Parameters
    ----------
    w : array_like
        Raw upward velocity [cm/s].

    Returns
    -------
    w_mps : ndarray
        Upward velocity VELPTTU-VLU_L1 [m/s].
    """
    return w / 100.0


def nortek_mag_corr_east(u, v, lat, lon, timestamp, z=0.0, status_code=0):
    """
    OOI wrapper for VELPTTU-VLE_L1 eastward velocity from VEL3D-C/D (Vector).

    Converts units from mm/s to m/s, calls vel_mag_correction to apply
    the WMM magnetic declination rotation, then applies optional status
    code scaling via nortek_scale_velocity.

    Parameters
    ----------
    u : array_like
        Uncorrected eastward velocity in magnetic Earth frame [mm/s].
    v : array_like
        Uncorrected northward velocity in magnetic Earth frame [mm/s].
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    z : float or array_like, optional
        Depth of instrument relative to sea level [m], positive values
        only. Default is 0.
    status_code : int or array_like, optional
        Status code variable from the instrument system packet. If bit 1
        is set, velocity is scaled by 0.1. Default is 0.

    Returns
    -------
    u_cor : ndarray
        Eastward velocity VELPTTU-VLE_L1 in true Earth frame [m/s].

    Notes
    -----
    As of 2015-06-08, the DPS (1341-00780) is still incorrect: the
    Nortek Vector outputs its velocities in units of mm/s.

    See Also
    --------
    vel_mag_correction : Core algorithm; use directly for multi-output
        access.
    """
   # check for valid latitudes & longitudes
    if not valid_lat(lat) or not valid_lon(lon):
        # commented out next line according to NOTE above. -SP
        #return np.ones(u.shape, dtype=float) * -9999
        raise ValueError('Latitudes or Longitudes are not within the valid range!')

    # change the units of the input velocities from mm/sec (see Notes) to m/sec
    u = u / 1000.0
    v = v / 1000.0

    # correct for magnetic declination
    u_cor = vel_mag_correction(u, v, lat, lon, timestamp, z)[0]

    u_cor = nortek_scale_velocity(u_cor, status_code)

    # return true compass referenced East velocity in m/s
    return u_cor


def nortek_mag_corr_north(u, v, lat, lon, timestamp, z=0.0, status_code=0):
    """
    OOI wrapper for VELPTTU-VLN_L1 northward velocity from VEL3D-C/D (Vector).

    Converts units from mm/s to m/s, calls vel_mag_correction to apply
    the WMM magnetic declination rotation, then applies optional status
    code scaling via nortek_scale_velocity.

    Parameters
    ----------
    u : array_like
        Uncorrected eastward velocity in magnetic Earth frame [mm/s].
    v : array_like
        Uncorrected northward velocity in magnetic Earth frame [mm/s].
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    z : float or array_like, optional
        Depth of instrument relative to sea level [m], positive values
        only. Default is 0.
    status_code : int or array_like, optional
        Status code variable from the instrument system packet. If bit 1
        is set, velocity is scaled by 0.1. Default is 0.

    Returns
    -------
    v_cor : ndarray
        Northward velocity VELPTTU-VLN_L1 in true Earth frame [m/s].

    Notes
    -----
    As of 2015-06-08, the DPS (1341-00780) is still incorrect: the
    Nortek Vector outputs its velocities in units of mm/s.

    See Also
    --------
    vel_mag_correction : Core algorithm; use directly for multi-output
        access.
    """
   # check for valid latitudes & longitudes
    if not valid_lat(lat) or not valid_lon(lon):
        # commented out next line according to NOTE above. -SP
        #return np.ones(u.shape, dtype=float) * -9999
        raise ValueError('Latitudes or Longitudes are not within the valid range!')

    # change the units of the input velocities from mm/sec (see Notes) to m/sec
    u = u / 1000.0
    v = v / 1000.0

    # correct for magnetic declination
    v_cor = vel_mag_correction(u, v, lat, lon, timestamp, z)[1]

    v_cor = nortek_scale_velocity(v_cor, status_code)

    # return true compass referenced North velocity in m/s
    return v_cor


def nortek_up_vel(w, status_code=0):
    """
    Compute VELPTTU-VLU_L1 upward velocity for VEL3D-C/D (Nortek Vector).

    Converts the upward velocity from the Nortek Vector instrument from
    mm/s to m/s, with optional status code scaling.

    Parameters
    ----------
    w : array_like
        Raw upward velocity [mm/s].
    status_code : int or array_like, optional
        Status code variable from the instrument system packet. If bit 1
        is set, velocity is scaled by 0.1. Default is 0.

    Returns
    -------
    w_l1 : ndarray
        Upward velocity VELPTTU-VLU_L1 [m/s].

    Notes
    -----
    As of 2015-06-08, the DPS (1341-00780) is still incorrect: the
    Nortek Vector outputs its velocities in units of mm/s.
    """
    return nortek_scale_velocity(w / 1000.0, status_code)


def nortek_scale_velocity(velocity, status_code=0):
    """
    Scale Nortek Vector velocity by 0.1 if bit 1 of status_code is set.

    Parameters
    ----------
    velocity : array_like
        Velocity to scale [any units].
    status_code : int or array_like, optional
        Status code from the instrument system packet. Default is 0.

    Returns
    -------
    velocity_scaled : ndarray
        Scaled velocity in the same units as input.
    """
    status_code = np.rint(status_code).astype(dtype=int)
    scale_factor = np.where(np.bitwise_and(status_code, 0x2).astype(dtype=bool), 0.1, 1.0)
    return velocity * scale_factor


def vel3dk_east(
        vel0, vel1, vel2, heading, pitch, roll, beams, lat, lon,
        timestamp, Vscale, z=0, vel3=0):
    """
    OOI wrapper for VELPTTU-VLE_L1 eastward velocity from VEL3D-K.

    Scales beam velocities, converts attitude variables from deci-degrees
    to degrees, calls vel3dk_transform, then applies vel_mag_correction
    to return the eastward component.

    Parameters
    ----------
    vel0 : array_like
        Beam 0 velocity as scaled integer counts.
    vel1 : array_like
        Beam 1 velocity as scaled integer counts.
    vel2 : array_like
        Beam 2 velocity as scaled integer counts.
    heading : array_like
        Instrument heading from the Aquadopp II [deci-degrees].
    pitch : array_like
        Instrument pitch from the Aquadopp II [deci-degrees].
    roll : array_like
        Instrument roll from the Aquadopp II [deci-degrees].
    beams : array_like
        Beam configuration as an Nx5 array listing the physical beams
        corresponding to vel0-vel3. The 5th column is ignored.
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    Vscale : int or float
        Velocity scaling exponent; velocities are multiplied by
        10^Vscale.
    z : float or array_like, optional
        Depth of instrument relative to sea level [m], positive values
        only. Default is 0.
    vel3 : array_like, optional
        Optional 4th beam velocity as scaled integer counts. Default 0
        (3-beam mode).

    Returns
    -------
    u_cor : ndarray
        Eastward velocity VELPTTU-VLE_L1 in true Earth frame [m/s].

    Notes
    -----
    The stationary (4-beam) transform has not been exercised in OOI
    deployments and is unverified.

    See Also
    --------
    vel3dk_transform : Core algorithm; use directly for full ENU output.
    """
    # convert from scaled, integer distance/s (as received from the
    # binary data file) to floating point m/s using the Vscale parameter
    # from the MMP binary data file A#####.DEC
    vel0 = vel0 * 10.**Vscale
    vel1 = vel1 * 10.**Vscale
    vel2 = vel2 * 10.**Vscale
    if vel3 != 0:
        vel3 = vel3 * 10.**Vscale

    # attitude variables are in deci-degrees (i.e. 0.1 degrees) and need
    # to be converted back to degrees.  I believe this is only true if
    # parsing the binary data file (as opposed to the ascii produced by
    # McLane's software)  Source: Aquadopp2 Integrators guide.
    heading = 0.1 * heading
    roll = 0.1 * roll
    pitch = 0.1 * pitch

   # check for valid latitudes & longitudes
    if not valid_lat(lat) or not valid_lon(lon):
        raise ValueError('Latitudes or Longitudes are not within the valid range!')

    # transform beam velocites in spherical coordinates to Earth
    # coordinates using beam configuration and instrument attitude.
    if vel3 != 0:
        ENU = vel3dk_transform(
            vel0, vel1, vel2, heading, pitch, roll, beams, vel3)
    else:
        ENU = vel3dk_transform(
            vel0, vel1, vel2, heading, pitch, roll, beams)

    # separate out the components from the Earth coordinate transformed
    # data matrix. The zero index is needed since matrix is
    # automatically 2-D, must change back to a 1-D array.
    u = np.array(ENU[0, :])[0]
    v = np.array(ENU[1, :])[0]

    # correct for magnetic declination
    u_cor = vel_mag_correction(u, v, lat, lon, timestamp, z)[0]

    # return true compass referenced East velocity in m/s
    #   the zero index is needed here because the vel3dk
    return u_cor


def vel3dk_north(
        vel0, vel1, vel2, heading, pitch, roll, beams, lat, lon,
        timestamp, Vscale, z=0, vel3=0):

    """
    OOI wrapper for VELPTTU-VLN_L1 northward velocity from VEL3D-K.

    Scales beam velocities, converts attitude variables from deci-degrees
    to degrees, calls vel3dk_transform, then applies vel_mag_correction
    to return the northward component.

    Parameters
    ----------
    vel0 : array_like
        Beam 0 velocity as scaled integer counts.
    vel1 : array_like
        Beam 1 velocity as scaled integer counts.
    vel2 : array_like
        Beam 2 velocity as scaled integer counts.
    heading : array_like
        Instrument heading from the Aquadopp II [deci-degrees].
    pitch : array_like
        Instrument pitch from the Aquadopp II [deci-degrees].
    roll : array_like
        Instrument roll from the Aquadopp II [deci-degrees].
    beams : array_like
        Beam configuration as an Nx5 array listing the physical beams
        corresponding to vel0-vel3. The 5th column is ignored.
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    Vscale : int or float
        Velocity scaling exponent; velocities are multiplied by
        10^Vscale.
    z : float or array_like, optional
        Depth of instrument relative to sea level [m], positive values
        only. Default is 0.
    vel3 : array_like, optional
        Optional 4th beam velocity as scaled integer counts. Default 0
        (3-beam mode).

    Returns
    -------
    v_cor : ndarray
        Northward velocity VELPTTU-VLN_L1 in true Earth frame [m/s].

    Notes
    -----
    The stationary (4-beam) transform has not been exercised in OOI
    deployments and is unverified.

    See Also
    --------
    vel3dk_transform : Core algorithm; use directly for full ENU output.
    """
    # convert from scaled, integer distance/s (as received from the
    # binary data file) to floating point m/s using the Vscale parameter
    # from the MMP binary data file A#####.DEC
    vel0 = vel0 * 10.**Vscale
    vel1 = vel1 * 10.**Vscale
    vel2 = vel2 * 10.**Vscale
    if vel3 != 0:
        vel3 = vel3 * 10.**Vscale

    # attitude variables are in deci-degrees (i.e. 0.1 degrees) and need
    # to be converted back to degrees.  I believe this is only true if
    # parsing the binary data file (as opposed to the ascii produced by
    # McLane's software)  Source: Aquadopp2 Integrators guide.
    heading = 0.1 * heading
    roll = 0.1 * roll
    pitch = 0.1 * pitch

   # check for valid latitudes & longitudes
    if not valid_lat(lat) or not valid_lon(lon):
        raise ValueError('Latitudes or Longitudes are not within the valid range!')

    # transform beam velocites in spherical coordinates to Earth
    # coordinates using beam configuration and instrument attitude.
    if vel3 != 0:
        ENU = vel3dk_transform(
            vel0, vel1, vel2, heading, pitch, roll, beams, vel3)
    else:
        ENU = vel3dk_transform(
            vel0, vel1, vel2, heading, pitch, roll, beams)

    # separate out the components from the Earth coordinate transformed
    # data matrix. The zero index is needed since matrix is
    # automatically 2-D, must change back to a 1-D array.
    u = np.array(ENU[0, :])[0]
    v = np.array(ENU[1, :])[0]

    # correct for magnetic declination
    v_cor = vel_mag_correction(u, v, lat, lon, timestamp, z)[1]

    # return true compass referenced East velocity in m/s
    return v_cor


def vel3dk_up(
        vel0, vel1, vel2, heading, pitch, roll, beams, Vscale, vel3=0):
    """
    OOI wrapper for VELPTTU-VLU_L1 upward velocity from VEL3D-K.

    Scales beam velocities, converts attitude variables from deci-degrees
    to degrees, calls vel3dk_transform, and returns the upward component.

    Parameters
    ----------
    vel0 : array_like
        Beam 0 velocity as scaled integer counts.
    vel1 : array_like
        Beam 1 velocity as scaled integer counts.
    vel2 : array_like
        Beam 2 velocity as scaled integer counts.
    heading : array_like
        Instrument heading from the Aquadopp II [deci-degrees].
    pitch : array_like
        Instrument pitch from the Aquadopp II [deci-degrees].
    roll : array_like
        Instrument roll from the Aquadopp II [deci-degrees].
    beams : array_like
        Beam configuration as an Nx5 array listing the physical beams
        corresponding to vel0-vel3. The 5th column is ignored.
    Vscale : int or float
        Velocity scaling exponent; velocities are multiplied by
        10^Vscale.
    vel3 : array_like, optional
        Optional 4th beam velocity as scaled integer counts. Default 0
        (3-beam mode).

    Returns
    -------
    w : ndarray
        Upward velocity VELPTTU-VLU_L1 [m/s].

    Notes
    -----
    The stationary (4-beam) transform has not been exercised in OOI
    deployments and is unverified.

    See Also
    --------
    vel3dk_transform : Core algorithm; use directly for full ENU output.
    """
    # convert from scaled, integer distance/s (as received from the
    # binary data file) to floating point m/s using the Vscale parameter
    # from the MMP binary data file A#####.DEC
    vel0 = vel0 * 10.**Vscale
    vel1 = vel1 * 10.**Vscale
    vel2 = vel2 * 10.**Vscale
    if vel3 != 0:
        vel3 = vel3 * 10.**Vscale

    # attitude variables are in deci-degrees (i.e. 0.1 degrees) and need
    # to be converted back to degrees.  I believe this is only true if
    # parsing the binary data file (as opposed to the ascii produced by
    # McLane's software)  Source: Aquadopp2 Integrators guide.
    heading = 0.1 * heading
    roll = 0.1 * roll
    pitch = 0.1 * pitch

    # transform the beam velocities to Earth coordinates
    if vel3 != 0:
        ENU = vel3dk_transform(
            vel0, vel1, vel2, heading, pitch, roll, beams, vel3)
    else:
        ENU = vel3dk_transform(
            vel0, vel1, vel2, heading, pitch, roll, beams)

    # seperate out the components from the
    w = np.array(ENU[2, :])[0]

    # return vertical velocity in m/s
    return w


def velpt_mag_corr_east(u, v, lat, lon, timestamp, z=0.0):
    """
    OOI wrapper for VELPTMN-VLE_L1 eastward velocity from VELPT-A/B/D/J.

    Converts units from mm/s to m/s and calls vel_mag_correction to
    apply the WMM magnetic declination rotation. Does not apply to
    VEL3D-K.

    Parameters
    ----------
    u : array_like
        Uncorrected eastward velocity in magnetic Earth frame [mm/s].
    v : array_like
        Uncorrected northward velocity in magnetic Earth frame [mm/s].
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    z : float or array_like, optional
        Depth of instrument relative to sea level [m], positive values
        only. Default is 0.

    Returns
    -------
    u_cor : ndarray
        Eastward velocity VELPTMN-VLE_L1 in true Earth frame [m/s].

    See Also
    --------
    vel_mag_correction : Core algorithm; use directly for multi-output
        access.
    """
   # check for valid latitudes & longitudes
    if not valid_lat(lat) or not valid_lon(lon):
        # commented out next line according to NOTE above. -SP
        #return np.ones(u.shape, dtype=float) * -9999
        raise ValueError('Latitudes or Longitudes are not within the valid range!')

    # correct for magnetic declination
    u_cor = vel_mag_correction(u, v, lat, lon, timestamp, z)[0]

    # return true compass referenced East velocity in m/s
    return u_cor / 1000.


def velpt_mag_corr_north(u, v, lat, lon, timestamp, z=0.0):
    """
    OOI wrapper for VELPTMN-VLN_L1 northward velocity from VELPT-A/B/D/J.

    Converts units from mm/s to m/s and calls vel_mag_correction to
    apply the WMM magnetic declination rotation. Does not apply to
    VEL3D-K.

    Parameters
    ----------
    u : array_like
        Uncorrected eastward velocity in magnetic Earth frame [mm/s].
    v : array_like
        Uncorrected northward velocity in magnetic Earth frame [mm/s].
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    z : float or array_like, optional
        Depth of instrument relative to sea level [m], positive values
        only. Default is 0.

    Returns
    -------
    v_cor : ndarray
        Northward velocity VELPTMN-VLN_L1 in true Earth frame [m/s].

    See Also
    --------
    vel_mag_correction : Core algorithm; use directly for multi-output
        access.
    """
   # check for valid latitudes & longitudes
    if not valid_lat(lat) or not valid_lon(lon):
        # commented out next line according to NOTE above. -SP
        #return np.ones(u.shape, dtype=float) * -9999
        raise ValueError('Latitudes or Longitudes are not within the valid range!')

    # correct for magnetic declination
    v_cor = vel_mag_correction(u, v, lat, lon, timestamp, z)[1]

    # return true compass referenced North velocity in m/s
    return v_cor / 1000.


def velpt_up_vel(w):
    """
    Compute VELPTMN-VLU_L1 upward velocity for VELPT-A/B/D/J (Aquadopp).

    Converts the upward velocity from Nortek Aquadopp instruments
    (VELPT series A/B/D/J) from mm/s to m/s. Does not apply to VEL3D-K.

    Parameters
    ----------
    w : array_like
        Raw upward velocity [mm/s].

    Returns
    -------
    w_mps : ndarray
        Upward velocity VELPTMN-VLU_L1 [m/s].
    """
    return w / 1000.


##### Sub functions #####
## VEL3D-A,L subfunctions ##
def fsi_acm_horz_vel(vp1, vp3, hdg, lat, lon, timestamp):
    """
    Compute horizontal ENU velocities for VEL3D series A and L (FSI ACM).

    Converts raw beam velocities vp1 and vp3 from the FSI ACM stinger
    configuration to eastward and northward velocity components in true
    Earth coordinates, corrected for magnetic declination.

    Parameters
    ----------
    vp1 : array_like
        Raw beam velocity from the port stinger finger;
        VELPTMN-VP1_L0 [cm/s].
    vp3 : array_like
        Raw beam velocity from the starboard stinger finger;
        VELPTMN-VP3_L0 [cm/s].
    hdg : array_like
        ACM nautical heading [degrees clockwise from magnetic north to
        the instrument x-axis].
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].

    Returns
    -------
    u : ndarray
        Eastward velocity in true Earth coordinates [m/s].
    v : ndarray
        Northward velocity in true Earth coordinates [m/s].

    Notes
    -----
    The FSI ACM stinger has 4 fingers oriented 45 deg from a central
    post so that their tips describe a square. The instrument x-axis
    runs along the central post away from the profiler; y is to port of
    x; z is up. vp1 (port) and vp3 (starboard) lie in the horizontal
    plane and are used for horizontal velocity.

    The beam-to-instrument transform is:

        Vx = (-vp1 - vp3) / sqrt(2)
        Vy = (vp1 - vp3) / sqrt(2)

    Pitch and roll are negligible for profiler-mounted instruments, so
    the instrument-to-earth transform involves only a heading correction
    combined with the WMM magnetic declination.

    For series A (RSN), hdg is derived from calibrated field direction
    cosines by fsi_acm_nautical_heading. For series L (Scripps), hdg
    is reported directly by the instrument.
    """
    # convert from beam coordinates to instrument coordinates
    Vx = (-vp1 - vp3) / np.sqrt(2.0)
    Vy = (vp1 - vp3) / np.sqrt(2.0)

    # find the speed; change units from cm/s to m/s
    speed = 0.01 * np.sqrt(Vx*Vx + Vy*Vy)

    # get the magnetic variation:
    # degrees clockwise from geographic north to magnetic north are positive.
    # degrees counter-clockwise from geographic north to magnetic north are negative.
    magvar = magnetic_declination(lat, lon, timestamp)

    # figure out the cartesian heading theta of the velocity vector (Vx, Vy) in the earth frame,
    # which is the angle defined as radians ccw from geographic east to the velocity vector.
    #    (1) in instrument coordinates the cartesian heading is atan2(Vy/Vx) [radians ccw from x-axis]
    #    (2) the nautical (magnetic) heading of the instrument's x-axis is converted to cartesian.
    #    (3) the magnetic variation corrections for nautical headings change sign when correcting
    #        cartesian headings because nautical headings become more positive in the clockwise
    #        direction, cartesian headings are more positive moving counterclockwise.
    theta_cartesian = np.arctan2(Vy, Vx) + np.deg2rad((90.0 - hdg) - magvar)

    #    (4) the MMP manual defines magvar using the opposite of the standard sign convention as
    #        described above. the manual adds their mdev (=magvar) to the cartesian heading, which
    #        is correct given their sign convention.
    #    (5) note: the version of the Scripps code I saw adds nautical heading values supplied by
    #        the ACM to the cartesian angle of the velocity vector (Vx, Vy), which is incorrect.

    # calculate the eastward (u) and northward (v) velocities
    u = speed * np.cos(theta_cartesian)
    v = speed * np.sin(theta_cartesian)

    return u, v


def fsi_acm_nautical_heading(hx, hy, hdg_cal, hx_cal, hy_cal):
    """
    Compute ACM compass headings from field direction cosines and calibration.

    Derives nautical headings from field direction cosines (hx, hy) using
    an 8-point spin test compass calibration. Used only for VEL3D series A
    instruments (FSI ACMs deployed by RSN).

    Parameters
    ----------
    hx : array_like
        Direction cosine of the local magnetic field projected onto the
        instrument x-axis.
    hy : array_like
        Direction cosine of the local magnetic field projected onto the
        instrument y-axis.
    hdg_cal : array_like
        8-element vector of reference ACM headings from a compass
        calibration spin test [degrees clockwise from magnetic north].
    hx_cal : array_like
        8-element vector of direction cosines of the magnetic field
        projected along the instrument x-axis during a calibration spin.
    hy_cal : array_like
        8-element vector of direction cosines of the magnetic field
        projected along the instrument y-axis during a calibration spin.

    Returns
    -------
    hdg_nautical : ndarray
        Heading values [degrees clockwise from magnetic north to the
        instrument x-axis], in [0, 360).

    Notes
    -----
    Calibration correction parameters (offsets, scale factors, compass
    bias) are computed by fsi_acm_compass_cal and applied to the field
    direction cosines before the heading is derived from atan2(hx/hy).
    See the MMP manual (p. 8-18 and Appendix D) for the calibration
    procedure.
    """
    # calculate the compass cal correction values
    (hx_offset, hy_offset, hx_scale, hy_scale, compass_bias) = fsi_acm_compass_cal(
        hdg_cal, hx_cal, hy_cal)

    # correct the field direction cosine data.
    hxcorr = (hx-hx_offset)/hx_scale
    hycorr = (hy-hy_offset)/hy_scale

    # calculate cartesian heading as per manual: atan2(hxcorr/hycorr) and not as y/x.
    # this heading is the orientation of the instrument x-axis in degrees ccw from
    # magnetic east. using this convention, the compass bias correction is added to
    # the cartesian heading.
    hdg_cartesian = np.rad2deg(np.arctan2(hxcorr, hycorr)) + compass_bias

    # convert to the nautical heading convention
    hdg_nautical = 90.0 - hdg_cartesian
    # and make sure values lie in [0 360)
    hdg_nautical = np.mod(360.0 + hdg_nautical, 360.0)

    return hdg_nautical


def fsi_acm_compass_cal(hdg_cal, hx_cal, hy_cal):
    """
    Compute compass calibration parameters from an 8-point spin test.

    Calculates offsets, scaling factors, and a compass bias from
    calibration direction cosines acquired during a spin test for FSI
    ACM instruments. Used only for VEL3D series A instruments (RSN).

    Parameters
    ----------
    hdg_cal : array_like
        8-element vector of reference ACM headings from a compass
        calibration spin test [degrees clockwise from magnetic north].
        Spacing should be 45 degrees.
    hx_cal : array_like
        8-element vector of direction cosines of the magnetic field
        projected along the instrument x-axis during the calibration.
    hy_cal : array_like
        8-element vector of direction cosines of the magnetic field
        projected along the instrument y-axis during the calibration.

    Returns
    -------
    hx_offset : ndarray
        Subtractive correction offset for the hx direction cosine.
    hy_offset : ndarray
        Subtractive correction offset for the hy direction cosine.
    hx_scale : ndarray
        Multiplicative scaling correction for the hx direction cosine.
    hy_scale : ndarray
        Multiplicative scaling correction for the hy direction cosine.
    compass_bias : ndarray
        Additive correction to derived cartesian heading values [degrees].

    Notes
    -----
    The 8 compass points should be equidistantly spaced around a circle.
    The anticipated RSN ACM calibration headings are 335, 20, 65, 110,
    155, 200, 245, 290 degrees.

    If no calibration is available, default cal values producing zero
    offsets and biases and unit scaling factors can be used:

        hdg_cal  hx_cal   hy_cal
           0      1.0      0.0
          45      1.0      1.0
          90      0.0      1.0
         135     -1.0      1.0
         180     -1.0      0.0
         225     -1.0     -1.0
         270      0.0     -1.0
         315      1.0     -1.0
    """
    # make sure that the cal variables are sized correctly.
    # variables should be passed to DPAs as 2D vectors, but make sure to avoid tuple out of range.
    hdg_cal = np.atleast_2d(hdg_cal)
    hx_cal = np.atleast_2d(hx_cal)
    hy_cal = np.atleast_2d(hy_cal)
    lFlag = hdg_cal.shape[1] != 8 or hx_cal.shape[1] != 8 or hy_cal.shape[1] != 8
    if lFlag:
        raise ValueError('Each row of the compass calibration variables hdg_cal, '
                         'hx_cal, and hy_cal must contain 8 elements.')

    # the offsets are found by taking the vector average.
    # return column vectors so that python's default broadcasting action will give desired result.
    hx_offset = np.mean(hx_cal, axis=1, keepdims=True)
    hy_offset = np.mean(hy_cal, axis=1, keepdims=True)

    # the scaling factors are calculated as
    hx_scale = np.max(np.abs(hx_cal - hx_offset), axis=1, keepdims=True)
    hy_scale = np.max(np.abs(hy_cal - hy_offset), axis=1, keepdims=True)

    # the x and y offsets and scaling factors will be used to correct the field data.

    # they are also used to find the average compass bias (BT in the MMP manual);
    # first correct the cal direction cosines (same procedure as is used to correct the
    # field data).
    hxcalcorr = (hx_cal-hx_offset)/hx_scale
    hycalcorr = (hy_cal-hy_offset)/hy_scale
    # convert nautical heading to cartesian
    hdg_cal_cartesian = 90.0 - hdg_cal
    # arctan(hx/hy) is correct because of the instrument axes and heading conventions.
    # the np.arctan2 function takes the 'y' coordinate first, which in this case is hx.
    compass_bias = hdg_cal_cartesian - np.rad2deg(np.arctan2(hxcalcorr, hycalcorr))
    # correct compass differences resulting from the wrap-around discontinuity
    mask = np.abs(compass_bias) > 180.0
    compass_bias[mask] = compass_bias[mask] - np.sign(compass_bias[mask]) * 360.0
    # and take the mean, final answer. for symmetry, return answer as a column vector, but ...
    compass_bias = np.mean(compass_bias, axis=1, keepdims=True)

    # now return all arguments as 1D arrays.
    hx_offset = hx_offset.reshape(-1)
    hy_offset = hy_offset.reshape(-1)
    hx_scale = hx_scale.reshape(-1)
    hy_scale = hy_scale.reshape(-1)
    compass_bias = compass_bias.reshape(-1)

    return hx_offset, hy_offset, hx_scale, hy_scale, compass_bias


## VEL3D-K Beam coordinate transformations ##
def generate_beam_transforms():
    """
    Generate beam-to-profiler-cartesian transform matrices for VEL3D-K.

    Creates the three possible beam-to-cartesian coordinate transform
    matrices for the Nortek Aquadopp II (VEL3D-K) on a McLane Moored
    Profiler, corresponding to upward-traveling profiles (beams 1, 2, 4),
    downward-traveling profiles (beams 2, 3, 4), and stationary
    measurements (all 4 beams). Returns a dictionary keyed by 'upward',
    'downward', and 'stationary'.

    Returns
    -------
    beam2XYZ_transforms : dict
        Dictionary with keys 'upward', 'downward', and 'stationary',
        each containing a numpy matrix for transforming beam velocities
        to profiler Cartesian (XYZ) coordinates.

    Notes
    -----
    Transducer azimuthal angles increase in the counter-clockwise
    direction (1 -> 4 -> 3 -> 2). Elevation angles are 47.5 deg for
    beams 1 and 3, and 25 deg for beams 2 and 4.

    The stationary (4-beam) transform has not been exercised in OOI
    deployments and is unverified.

    The 2018 revision corrected three errors from the original 2014
    Nortek-supplied code: (1) azimuthal angles were previously defined
    clockwise (left-handed coordinate system); (2) pitch values were
    incorrectly negated; (3) heading values were not offset by 90 deg
    to account for the Aquadopp II heading reference being the
    instrument X-axis.
    """
    ## INTERNAL DESCRIPTION:
    ## First a matrix that transforms the velocities from cartesian
    ## coordinates to spherical beam coordinates is created (identified
    ## by the xyz2beam). To find the reverse matrix that transforms the
    ## velocities from spherical beams to cartesian coordinates, the
    ## inverse of the first matrix must be found (identified by
    ## beam2xyz). This is known as a "Change of basis". The permutation
    ## matrix then transforms the velocities from cartesian coordianates
    ## of the instrument, to cartesian coordinates of the profiler. The
    ## permutation matrix is muliplied by the beam2xyz to get the single
    ## transformation matrix beam2XYZ (capital XYZ indicates cartesian
    ## coordinates of the profiler). To get to Earth coordinates,
    ## another transformation matrix that reverses heading, pitch, and
    ## roll must be made, but that occurs in another function.

    # BEAMS dictionary is the rotations for each beam from cartesian
    # coordinates to spherical coordinates
    #
    ### RDesiderio: change code so that increasing azimuthal angle is in
    ### the counter-clockwise direction 1 -> 4 -> 3 -> 2.
    BEAMS = {
        1: (sin(radians(47.5)) * cos(radians(0.0)),
            0.0,  # sin(47.5 deg)*sin(0 deg) = 0
            cos(radians(47.5))),
        2: (0.0,  # sin(25 deg)*cos(270 deg) = 0
            sin(radians(25.0)) * sin(radians(270.0)),
            cos(radians(25.0))),
        3: (sin(radians(47.5)) * cos(radians(180.0)),
            0.0,  # sin(47.5 deg)*sin(180 deg) = 0
            cos(radians(47.5))),
        4: (0.0,  # sin(25 deg)*cos(90 deg) = 0
            sin(radians(25.0)) * sin(radians(90.0)),
            cos(radians(25.0)))}

    # the cartesian to beam transforms
    upward_xyz2beam = np.matrix([BEAMS[1], BEAMS[2], BEAMS[4]])
    downward_xyz2beam = np.matrix([BEAMS[2], BEAMS[3], BEAMS[4]])
    stationary_xyz2beam = np.matrix([
        [BEAMS[1][0], BEAMS[1][1], BEAMS[1][2], 0.0],
        [BEAMS[2][0], BEAMS[2][1], 0.0, BEAMS[2][2]],
        [BEAMS[3][0], BEAMS[3][1], BEAMS[3][2], 0.0],
        [BEAMS[4][0], BEAMS[4][1], 0.0, BEAMS[4][2]]])

    # get the inverse of the transforms
    upward_beam2xyz = np.linalg.pinv(upward_xyz2beam)
    downward_beam2xyz = np.linalg.pinv(downward_xyz2beam)
    stationary_beam2xyz = np.linalg.pinv(stationary_xyz2beam)

    # set ~0 float point errors to zero
    upward_beam2xyz[abs(upward_beam2xyz) < 1e-15] = 0.0
    downward_beam2xyz[abs(downward_beam2xyz) < 1e-15] = 0.0
    stationary_beam2xyz[abs(stationary_beam2xyz) < 1e-15] = 0.0

    # create permutation matrices
    permutation_matrix3 = np.matrix([  # if 3 beams are used
        [0,  0, 1],
        [0, -1, 0],
        [1,  0, 0]
    ])
    permutation_matrix4 = np.matrix([  # if 4 beams are used
        [0,  0, 0.5, 0.5],
        [0, -1,   0,   0],
        [1,  0,   0,   0]
    ])

    # combine to create the beam2XYZ (profiler cartesian) transformation
    T_beam2XYZ_up = permutation_matrix3 * upward_beam2xyz
    T_beam2XYZ_down = permutation_matrix3 * downward_beam2xyz
    T_beam2XYZ_stat = permutation_matrix4 * stationary_beam2xyz

    beam2XYZ_transforms = {'upward': T_beam2XYZ_up,
                           'downward': T_beam2XYZ_down,
                           'stationary': T_beam2XYZ_stat}

    return beam2XYZ_transforms


# XYZ_TRANSFORMS constant created here
XYZ_TRANSFORMS = generate_beam_transforms()


def get_XYZ_transform(beamlist):
    """
    Retrieve the beam-to-profiler-cartesian transform for a given beam config.

    Selects the appropriate pre-computed transform matrix from the
    XYZ_TRANSFORMS module constant based on the beam configuration list
    for a profile.

    Parameters
    ----------
    beamlist : list
        List of physical beam numbers used in order, e.g. [1, 2, 4, 0]
        for an upward-traveling profile.

    Returns
    -------
    t_beam2XYZ : numpy.matrix
        Beam-to-profiler-cartesian transform matrix.

    Notes
    -----
    Valid beam configurations are [1, 2, 4, 0] (upward), [2, 3, 4, 0]
    (downward), and [1, 2, 3, 4] (stationary). The stationary case
    prints a warning and has not been verified in OOI deployments.
    """
    ## Implemented by:
    ## 2014-05-13: Stuart Pearce. Reimplementation of code from P.J.
    ##     Rusello at Nortek
    if beamlist == [1, 2, 3, 4]:
        t_beam2XYZ = XYZ_TRANSFORMS['stationary']
        print('WARNING: STATIONARY VEL3D-K TRANSFORMS ARE NOT VETTED.')
    elif beamlist == [1, 2, 4, 0]:
        t_beam2XYZ = XYZ_TRANSFORMS['upward']
    elif beamlist == [2, 3, 4, 0]:
        t_beam2XYZ = XYZ_TRANSFORMS['downward']

    return t_beam2XYZ


def generate_ENU_transform(heading, pitch, roll):
    """
    Generate profiler-cartesian to Earth ENU transform for VEL3D-K.

    Constructs the rotation matrix that transforms velocity vectors from
    profiler Cartesian (XYZ) coordinates to Earth coordinates (East,
    North, Up) using heading, pitch, and roll from the Aquadopp II.

    Parameters
    ----------
    heading : float
        Instrument heading [degrees]. The Aquadopp II heading reference
        is the instrument X-axis; 90 deg is subtracted before the
        rotation matrix is constructed.
    pitch : float
        Instrument pitch [degrees].
    roll : float
        Instrument roll [degrees].

    Returns
    -------
    XYZ2ENU : numpy.matrix
        3x3 rotation matrix transforming profiler XYZ to Earth ENU.

    Notes
    -----
    The 2018 revision corrected two errors in the 2014 code: (1) pitch
    values were incorrectly negated; (2) heading was not offset by 90 deg
    to account for the Aquadopp II heading reference being the X-axis
    rather than the Y-axis.
    """
    ### RDesiderio: Because the heading measured by the AQDII is with reference
    ### to the instrument 'X' axis relative to magnetic north, the measured
    ### values need to be corrected by subtracting 90 degrees.
    heading = np.radians(heading - 90)
    # need to make pitch and roll angles negative so that rotation matrices
    # effectively unpitch and unroll the data
    ### RDesiderio: the de facto definition of pitch for this instrument
    ### requires an additional negation resulting in no net negation.
    pitch = np.radians(pitch)
    roll = np.radians(-1.0 * roll)

    # "un"-roll transform matrix
    Rx = np.matrix([
        [1.0, 0.0, 0.0],
        [0.0, cos(roll), sin(roll)],
        [0.0, -sin(roll), cos(roll)]]
    )
    # "un"-pitch transform matrix
    Ry = np.matrix([
        [cos(pitch), 0.0, -sin(pitch)],
        [0.0, 1.0, 0.0],
        [sin(pitch), 0.0, cos(pitch)]]
    )
    # "un"-heading transform matrix
    Rz = np.matrix([
        [cos(heading), sin(heading), 0.0],
        [-sin(heading), cos(heading), 0.0],
        [0.0, 0.0, 1.0]]
    )

    # multiply together to create the XYZ to Earth coordinate transform
    XYZ2ENU = Rz * Ry * Rx
    return XYZ2ENU


def vel3dk_transform(
        vel0, vel1, vel2, heading, pitch, roll, beams, vel3=0):
    """
    Transform VEL3D-K beam velocities to Earth ENU coordinates.

    Transforms 3 or 4 beam velocities from the Nortek Aquadopp II
    (VEL3D-K) on a McLane Moored Profiler to Earth coordinates (East,
    North, Up), uncorrected for magnetic declination.

    Parameters
    ----------
    vel0 : array_like
        Beam 0 velocity [m/s].
    vel1 : array_like
        Beam 1 velocity [m/s].
    vel2 : array_like
        Beam 2 velocity [m/s].
    heading : array_like
        Instrument heading [degrees].
    pitch : array_like
        Instrument pitch [degrees].
    roll : array_like
        Instrument roll [degrees].
    beams : array_like
        Beam configuration as an Nx5 array. The 5th column is ignored.
        Rows containing the integer fill value (-999999999) produce NaN
        outputs.
    vel3 : array_like, optional
        Optional 4th beam velocity [m/s]. Default 0 (3-beam mode).

    Returns
    -------
    ENU : numpy.matrix
        3 x N matrix of Earth coordinate velocities (East, North, Up)
        uncorrected for magnetic declination. Rows corresponding to beam
        configuration fill values contain NaN.

    Notes
    -----
    The integer fill value for beam configuration variables is
    -999999999. Rows in the beams array containing this value are
    excluded from the transform and produce NaN in the output. The 5th
    beam column is discarded before processing.
    """
    # denote the agreed upon fill value for all integer variables.
    fill = -999999999
    # at some point this will probably become a global variable.

    # Ensure that the variables are in the right condition
    heading = np.atleast_1d(heading)
    roll = np.atleast_1d(roll)
    pitch = np.atleast_1d(pitch)
    beams = np.atleast_2d(beams)

    # if the array dimension of the vels are greater than 1, it will
    # break the call to np.matrix below.
    vel0 = np.atleast_1d(vel0)
    if vel0.ndim > 1:
        vel0 = np.reshape(vel0, -1)  # -1 auto-reshapes to 1 dimension
    vel1 = np.atleast_1d(vel1)
    if vel1.ndim > 1:
        vel1 = np.reshape(vel1, -1)
    vel2 = np.atleast_1d(vel2)
    if vel2.ndim > 1:
        vel2 = np.reshape(vel2, -1)

    # build the vels into a data matrix for matrix math coming up.
    # Each velocity is a row in this case so that later a 3x1 column
    # vector is produced for each record
    data = np.matrix([vel0, vel1, vel2])

    # Not likely to happen, but if a 4th beam is ever added,
    if vel3 != 0:
        vel3 = np.atleast_1d(vel3)
        if vel3.ndim > 1:
            vel3 = np.reshape(vel3, -1)
        # change the next statement from
        #data[4, :] = vel3
        # to
        data = np.vstack((data, vel3))

    # if the beams array has 5 beams, drop the 5th one since there is
    # not a 5th transducer.
    rows, cols = beams.shape
    if cols == 5:
        beams = np.delete(beams, 4, 1)
    else:
        raise ValueError(
            "the VEL3D-K algorithm inputs expect a Nx5 beam array," +
            "instead got a %dx%d array" % (rows, cols))

    # the next section traps out rows in the beams configuration variable that contain
    # the integer fill value; the corresponding columns in the product matrix ENU will
    # contain NaNs.

    # initialize output variable with nans
    ENU = np.matrix(np.ones_like(data)) * np.nan  # East, North, Up velocities

    # find rows in the (now) 4-column beams variable that do not contain fill values.
    mask = ~np.any(beams == fill, axis=1)
    # if all of the rows contained fill values, we're done;
    # for this case, return nans for all values.
    if np.all(~mask):
        return ENU

    # else, send only those data corresponding to good beams data for further processing
    beams = beams[mask, :]
    heading = heading[mask]
    pitch = pitch[mask]
    roll = roll[mask]
    data = data[:, mask]
    # initialize loop product variable
    ENU_loop = np.matrix(np.ones_like(data)) * np.nan  # East, North, Up velocities

    # Now grab the first beam configuration and the transform to start
    beams_used = list(beams[0, :])
    t_beam2XYZ = get_XYZ_transform(beams_used)

    # need a transformation matrix for each measurement
    # because Heading Pitch & Roll will change with each record
    for ii in range(np.size(heading)):
        if list(beams[ii, :]) != beams_used:
            beams_used = list(beams[ii, :])
            t_beam2XYZ = get_XYZ_transform(beams_used)
        t_XYZ2ENU = generate_ENU_transform(heading[ii], pitch[ii], roll[ii])
        ENU_loop[:, ii] = t_XYZ2ENU * t_beam2XYZ * data[:, ii]

    # now insert calculated loop product into output variable
    ENU[:, mask] = ENU_loop

    return ENU


## magnetic correction subfunction
def vel_mag_correction(u, v, lat, lon, ntp_timestamp, z=0.0, zflag=-1):
    """
    Apply magnetic declination correction to horizontal velocity components.

    Rotates a velocity vector (u, v) referenced to magnetic North into
    true Earth coordinates by removing the magnetic declination estimated
    from the World Magnetic Model (WMM) for the given location and time.

    Parameters
    ----------
    u : array_like
        Uncorrected eastward velocity in magnetic Earth frame.
    v : array_like
        Uncorrected northward velocity in magnetic Earth frame.
    lat : float or array_like
        Latitude of the instrument [decimal degrees]. North is positive.
    lon : float or array_like
        Longitude of the instrument [decimal degrees]. East is positive.
    ntp_timestamp : float or array_like
        NTP timestamp [seconds since 1900-01-01].
    z : float or array_like, optional
        Depth or height of the instrument relative to sea level [m],
        positive values only. Default is 0.
    zflag : int, optional
        Indicates whether z is depth (-1) or height above sea level
        (+1). Default is -1 (depth).

    Returns
    -------
    u_cor : ndarray
        Eastward velocity corrected to true Earth frame.
    v_cor : ndarray
        Northward velocity corrected to true Earth frame.

    Notes
    -----
    Magnetic declination is computed via
    generic_functions.magnetic_declination and is defined as positive
    when magnetic north is east of true north. The rotation applied is:

        u_cor = u * cos(theta) + v * sin(theta)
        v_cor = v * cos(theta) - u * sin(theta)
    """
    # retrieve the magnetic declination
    theta = magnetic_declination(lat, lon, ntp_timestamp, z, zflag)

    # apply the magnetic declination correction
    magvar = np.vectorize(magnetic_correction)
    u_cor, v_cor = magvar(theta, u, v)

    return u_cor, v_cor


# helper sub-functions
def valid_lat(lat):
    """
    Check whether lat values are within the valid range [-90, 90].

    Parameters
    ----------
    lat : float or array_like
        Latitude value(s) to check [decimal degrees].

    Returns
    -------
    valid : bool
        True if all values are in [-90, 90], False otherwise.
    """
    if isinstance(lat, np.ndarray):
        if np.any(lat > 90) or np.any(lat < -90):
            return False
        return True
    else:
        return -90 <= lat and lat <= 90


def valid_lon(lon):
    """
    Check whether lon values are within the valid range [-180, 180].

    Parameters
    ----------
    lon : float or array_like
        Longitude value(s) to check [decimal degrees].

    Returns
    -------
    valid : bool
        True if all values are in [-180, 180], False otherwise.
    """
    if isinstance(lon, np.ndarray):
        if np.any(lon > 180) or np.any(lon < -180):
            return False
        return True
    else:
        return -180 <= lon and lon <= 180
